spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mariadb://localhost:3306/cfm_mi?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

---
server:
  port: 8987
  contextPath:
---

JWT_KEY: RVZOSUNUMTFDVUFCQUM=
JWT_ISSUER: CFM
JWT_TIMEOUT: 360
JWT_COUNTER: 3
###

PASS.ACC: false


